### ISSUE TITLE
Unless I'm crazy, on Grid the Famicom (JP) and SNES (US) systems have 3 columns instead of 4.

### ISSUE THREAD

**Issue by notNSANE** [Siddy212/iconic-es-de#12]
Not sure why this happens. I'm on windows, 1080p, and everything as default except that I switched to Grid: Boxart

**Comment by notNSANE** [comment]
OK, it seems the SNES has really wide horizontal boxart, maybe the same with Famicom but haven't tested that one again. I wonder if there's an easy way to fix this or just take the hit and move on.

**Comment by notNSANE** [comment]
Also, Canvas has the same "issue".

BTW your themes are fantastic, I tried them all and decided to keep only Canvas and Iconic. They're just perfect for 1080p on PC.

**Comment by Siddy212** [comment]
Hey, I think I responded to this in Discord, but this is intentional. The coversizes are the default that ES-DE uses so it references 4-3 for Famicom. 3-4 is used for the NES variants. You can manually change this if you wish by editing the system metadata within the theme. Glad you like the themes!

**Comment by notNSANE** [comment]
hi! forgot to close this one. Thanks!
